name: Nahlášení Chyby
description: Nahlašte jakoukoli chybu, na kterou jste narazili pro zlepšení Serveru.
title: "[Chyba]: "
labels: ["chyba"]
body:
  - type: markdown
    attributes:
      value: |
        Děkujeme, že jste si vybrali čas pro vyplnění nahlášení!
  - type: textarea
    id: description
    attributes:
      label: Čistý a jednoduchý popis toho, co chyba je.
      description: Zároveň napiště, co jste očekávali, že se stane?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Kroky k opakování chyby
      description: Popište nám prosím kroky, které vedli k této chybě. Pomůže nám to s jejím řešením.
      value: |
        1. Připojil/a jsem se na server '...'
        2. Klikl/a jsem na '....'
        3. Použil/a jsem příkaz '....'
        4. Nastala chyba
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Obrázky
      description: Pokud je to možné, jakékoli obrázky, screenshoty pro lepší pochopení problému.
    validations:
        required: true   
  - type: dropdown
    id: platform
    attributes:
      label: Platforma
      description: |
        Platforma, nebo server kde problém nastal.
      options:
        - 🕸️ Web
        - 🧱 Minecraft (Globální na Všech Minecraft serverech)
        - 🛏️ BedWars
    validations:
        required: true
  - type: textarea
    id: additional
    attributes:
      label: Doplňující informace
      description: Jakékoli další doplňující informace, které nám chcete sdělit.
